In [37]:
#In exercise folder (same level as this notebook on github) there is hiring.csv. 
#This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. 
#Based on these 3 factors, HR will decide the salary. 
#Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. 
#Using this predict salaries for following candidates,

#2 yr experience, 9 test score, 6 interview score

#12 yr experience, 10 test score, 10 interview score

In [19]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [20]:
df=pd.read_csv(r"C:\Users\Dell\Desktop\ML\hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [21]:
df['test_score(out of 10)'].median()

8.0

In [22]:
df['test_score(out of 10)']= df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].median())

In [23]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [24]:
#to fill the NaN values
df.experience= df.experience.fillna("ten")

In [25]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        ten                    8.0                           9      50000
1        ten                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [26]:
new_salary=df['salary($)']
new_salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [27]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        ten                    8.0                           9      50000
1        ten                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [28]:
df.loc[df['experience']=='ten','experience']=10
df.loc[df['experience']=='five','experience']=5
df.loc[df['experience']=='two','experience']=2
df.loc[df['experience']=='seven','experience']=7
df.loc[df['experience']=='eleven','experience']=11
df.loc[df['experience']=='three','experience']=3
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         10                    8.0                           9      50000
1         10                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    8.0                           7      72000
7         11                    7.0                           8      80000

In [29]:
#create a linear_model object
reg= linear_model.LinearRegression()
reg.fit(df.drop('salary($)',axis='columns'),new_salary)

LinearRegression()

In [30]:
reg.coef_

array([129.51795038,  90.58161655, 405.14833853])

In [31]:
reg.intercept_

58157.12146355284

In [32]:
#for 2 yr experience, 9 test score, 6 interview score
reg.predict([[2,9.0,6]])

array([61662.28194439])

In [33]:
129.51795038*2+90.58161655*9.0+405.1483353*6+ 58157.12146355284

61662.28192506284

In [34]:
#for 12 yr experience, 10 test score, 10 interview score
reg.predict([[12,10.0,10]])

array([64668.63641883])

In [35]:
129.51795038*12+90.58161655+10.0+405.1483353*10+ 58157.12146355284

63863.40183766284